### ISSUE TITLE
How to using didselectrow to get the string name

### ISSUE THREAD

**Issue by renzrz** [tadija/AEAccordion#10]
Hello, i'm trying to get the header name of the selected row. But when i use `didSelectRowAt indexPath` what i get is empty string. How can i implement `didSelectRowAt` in this accordion?

**Comment by tadija** [comment]
Sorry, I'm not sure I understand, what's the "header name of the selected row"? Some custom label in your cell? Or section header? Or something else? :)

**Comment by renzrz** [comment]
Sorry for the unclear question sir.
I mean the section header.

In your example, there's a `textfield` inside section header  called `day`.
And when i touch or select the section header, i want to get the `string` from the `day.text` and store that `string` it into my variable.
How can i implement `didSelectRowAt` to get the `string` from the `day.text` and put it into variable?
Thank you beforehand.

**Comment by tadija** [comment]
In my example there is a `UILabel` inside a `UITableViewCell` which is named `day`.

That is not a **section header**, because table views actually use the term "section header" for a totally different thing, I suggest you read some docs about that.

To answer your question, you can simply implement `didSelectRowAt` like this to get the value you need:

```
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    super.tableView(tableView, didSelectRowAt: indexPath)
    print(days[indexPath.item])
}
```
